disabled_rules:
  - trailing_whitespace
  - force_cast
  - force_try
  - unused_setter_value
  - file_lenght
  - valid_ibinspectable
  - shorthand_operator
  - file_header
  - discarded_notification_center_observer
  - empty_enum_arguments
  - prohibited_super_call
  - missing_docs
  - unneeded_override

opt_in_rules:
  - empty_count
  - explicit_init
  - yoda_condition
  - closure_end_indentation
  - closure_spacing
  - fatal_error_message
  - first_where
  - operator_usage_whitespace
  - overriden_super_call
  - redundant_nil_coalescing
  - multiline_parameters
  - vertical_parameter_alignment_on_call
  - joined_default_parameter
  - unneeded_parenthesis_in_closure_argument


excluded:
  - Carthage/
  - Pods/
  - Generated/

# Rule to enforce camelCase for variable and constant names
identifier_name:
  min_length: 1
  max_length:
      warning: 50
      error: 60
  excluded: ["id", "url"]  # Exclude certain identifiers from the rule

# Rule to limit the length of function bodies
function_body_length:
  warning: 100
  error: 200

