# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NeoCafe Staff' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NeoCafe Staff
pod 'SnapKit'
pod 'SVPinView', '~> 1.0'
pod 'Moya/RxSwift', '~> 15.0'
pod 'SwiftGen'

end
