# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'NeoCafe Client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NeoCafe Client
pod 'SnapKit'
pod 'SwiftLint'
pod 'SVPinView', '~> 1.0'
pod 'Moya/RxSwift', '~> 15.0'
pod 'SwiftGen'
end
